#!/bin/bash

# Make sure to print each command
set -x

# Load environment variables
source .env


PREFIX=$PREFIX
CONTAINER_REGISTRY_NAME=$CONTAINER_REGISTRY_NAME
AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID
AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP
CONTAINER_REGISTRY_BASE=$AZURE_CONTAINER_REGISTRY_BASE

JUICE_SHOP_CONTAINER_IMAGE_NAME=$JUICE_SHOP_CONTAINER_IMAGE_NAME
JUICE_SHOP_CONTAINER_IMAGE_VERSION=$JUICE_SHOP_CONTAINER_IMAGE_VERSION
JUICE_SHOP_DEPLOYMENT_FILE=azure_aks_full_juice_shop.yaml


PYGOAT_DEPLOYMENT_FILE=azure_aks_short_pygoat.yaml
PYGOAT_CONTAINER_IMAGE_NAME=$PYGOAT_CONTAINER_IMAGE_NAME
PYGOAT_CONTAINER_IMAGE_VERSION=$PYGOAT_CONTAINER_IMAGE_VERSION

#* 1. Set Azure subscription
az account set --subscription $AZURE_SUBSCRIPTION_ID

#* 2. Login to Azure Container Registry
az acr login --name $CONTAINER_REGISTRY_NAME

#* 3. Docker pull image
#? Juice Shop
# docker pull europe-west2-docker.pkg.dev/ox-test-playground/juicehop/juice-shop:v1


#* 4. Docker tag image for Azure Container Registry
#? Juice Shop
docker tag europe-west2-docker.pkg.dev/ox-test-playground/juicehop/$JUICE_SHOP_CONTAINER_IMAGE_NAME:$JUICE_SHOP_CONTAINER_IMAGE_VERSION $CONTAINER_REGISTRY_NAME.$CONTAINER_REGISTRY_BASE/$JUICE_SHOP_CONTAINER_IMAGE_NAME:$JUICE_SHOP_CONTAINER_IMAGE_VERSION

#? PyGoat
docker tag pygoat/pygoat:latest $CONTAINER_REGISTRY_NAME.$CONTAINER_REGISTRY_BASE/$PYGOAT_CONTAINER_IMAGE_NAME:$PYGOAT_CONTAINER_IMAGE_VERSION


#* 5. Docker push image to Azure Container Registry
#? Juice Shop
docker push $CONTAINER_REGISTRY_NAME.$CONTAINER_REGISTRY_BASE/$JUICE_SHOP_CONTAINER_IMAGE_NAME:$JUICE_SHOP_CONTAINER_IMAGE_VERSION
#? PyGoat
docker push $CONTAINER_REGISTRY_NAME.$CONTAINER_REGISTRY_BASE/$PYGOAT_CONTAINER_IMAGE_NAME:$PYGOAT_CONTAINER_IMAGE_VERSION



#* 6. Attach ACR to AKS
az aks update -n $AZURE_KUBERNETES_CLUSTER -g $AZURE_RESOURCE_GROUP --attach-acr $CONTAINER_REGISTRY_NAME

#* 7. Deploy to AKS
kubectl apply -f k8s/$JUICE_SHOP_DEPLOYMENT_FILE
kubectl apply -f k8s/$PYGOAT_DEPLOYMENT_FILE



